# Set max bluetooth connections
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# Set passkey entry support (redundant with experimental_sec)
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# Set experimental security and connection stability features
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y

# Hardening configs
CONFIG_BOOT_BANNER=n
CONFIG_BUILD_OUTPUT_STRIPPED=y
CONFIG_FAULT_DUMP=0
CONFIG_HW_STACK_PROTECTION=y
CONFIG_MPU_STACK_GUARD=y
CONFIG_OVERRIDE_FRAME_POINTER_DEFAULT=y
CONFIG_STACK_SENTINEL=y
CONFIG_EARLY_CONSOLE=n
CONFIG_PRINTK=n
